import novelImg from "@/public/VNPlaceholder.jpg";

export let novelsData = [
  {
    title: "The Last Train",
    description: "A short visual novel about saying goodbye to the past.",
    imageUrl: novelImg,
    tgtLink: "https://shaunalachelier.itch.io/the-last-train",
    tags: ["Romance", "Drama", "Modern", "Celebrity", "Ongoing"],
  },
  {
    title: "Witch's Heart",
    description: "A story about a witch who is going to avenge her father.",
    imageUrl: novelImg,
    tgtLink: "https://fummy.itch.io/witchs-heart",
    tags: ["RPG", "Fantasy", "Magic", "Adventure", "Comedy", "Completed"],
  },
  {
    title: "Wanderlust",
    description: "A visual novel about exploring new places and meeting new people.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/wanderlust",
    tags: ["Girls' Love", "Modern", "Hurt-Comfort", "Slow Burn", "Hiatus"],
  },
  {
    title: "I'm the main antagonst?!",
    description: "A visual novel about a quest for a golden duck.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/golden-duck",
    tags: ["Reincarnation", "Isekai", "Comedy", "Villainess", "Completed"],
  },
  {
    title: "The world of the dead",
    description: "A visual novel about the world of the dead.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/world-of-the-dead",
    tags: ["Horror", "Supernatural", "Thriller", "Mystery", "Dystopian"],
  },
  {
    title: "Lost in the woods",
    description: "A visual novel about getting lost in the woods.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/lost-in-the-woods",
    tags: ["Thriller", "Survival", "Mystery", "Crime"],
  },
  {
    title: "The Last Train",
    description: "A short visual novel about saying goodbye to the past.",
    imageUrl: novelImg,
    tgtLink: "https://shaunalachelier.itch.io/the-last-train",
    tags: ["Modern", "Drama", "Tragedy", "Oneshot", "Completed"],
  },
  {
    title: "Witch's Heart",
    description: "A story about a witch who is going to avenge her father.",
    imageUrl: novelImg,
    tgtLink: "https://fummy.itch.io/witchs-heart",
    tags: ["Fantasy", "Adventure", "Magic", "Ongoing"],
  },
  {
    title: "Wanderlust",
    description: "A visual novel about exploring new places and meeting new people.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/wanderlust",
    tags: ["Adventure", "Mystery", "Overpowered MC", "Weak to Strong", "Completed"],
  },
  {
    title: "Where we Found Ourselves",
    description: "A visual novel about finding oneself in the world.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/where-we-found-ourselves",
    tags: ["Psychological", "Drama", "Mystery", "Adventure", "Slow Burn", "Hiatus"],
  },
  {
    title: "Rising to the Top",
    description: "An aspiring idol must work with her rival to reach the top.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/rising-to-the-top",
    tags: ["Girls' Love", "Celebrity", "Drama", "Comedy", "On-going"],
  },
  {
    title: "A Fanfiction Story",
    description: "A fanfiction story about a popular series.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/fanfiction-story",
    tags: ["Fan Work", "Romance", "Drama", "Sports", "Oneshot", "Completed"],
  }, 
];