import novelImg from "@/public/VNPlaceholder.jpg";

export let novelsData = [
  {
    title: "Falling with Style",
    description: "A visual novel about competing to be the best.",
    imageUrl: novelImg,
    tgtLink: "https://test.itch.io/falling-with-style",
    tags: ["Romance", "Drama", "Rivalry", "Celebrity", "Hurt-Comfort", "Ongoing"],
  },
  {
    title: "Dungeon Runners",
    description: "An interactive story about a group of adventurers in a fantasy world.",
    imageUrl: novelImg,
    tgtLink: "https://test.itch.io/dungeon-runners",
    tags: ["RPG", "Fantasy", "Magic", "Adventure", "Comedy", "Completed"],
  },
  {
    title: "We Are The Wanderers",
    description: "A visual novel about finding one's true purpose in a dystopian world.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/we-are-the-wanderers",
    tags: ["Adventure", "Modern", "Hurt-Comfort", "Dystopian", "Hiatus"],
  },
  {
    title: "The Final Frontier",
    description: "A space opera visual novel about exploring the universe.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/final-frontier",
    tags: ["Reincarnation", "Military", "Space Opera", "Comedy", "Sci-Fi", "Completed"],
  },
  {
    title: "The World of the Dead",
    description: "A visual novel about the world of the dead.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/world-of-the-dead",
    tags: ["Horror", "Supernatural", "Thriller", "Mystery", "Dystopian", "Ongoing"],
  },
  {
    title: "Lost in the Woods",
    description: "A visual novel about getting lost in the woods.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/lost-in-the-woods",
    tags: ["Thriller", "Survival", "Mystery", "Crime", "Ongoing"],
  },
  {
    title: "The Last Train",
    description: "A short visual novel about saying goodbye to the past.",
    imageUrl: novelImg,
    tgtLink: "https://shaunalachelier.itch.io/the-last-train",
    tags: ["Modern", "Drama", "Tragedy", "Oneshot", "Completed"],
  },
  {
    title: "Witch's Heart",
    description: "A story about a witch who is going to avenge her father.",
    imageUrl: novelImg,
    tgtLink: "https://fummy.itch.io/witchs-heart",
    tags: ["Fantasy", "Adventure", "Magic", "Ongoing"],
  },
  {
    title: "Wanderlust",
    description: "A visual novel about exploring new places and meeting new people.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/wanderlust",
    tags: ["Adventure", "Historical", "Hurt-Comfort", "Weak to Strong", "Completed"],
  },
  {
    title: "Fighting Against Time",
    description: "A visual novel about running against the clock.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/where-we-found-ourselves",
    tags: ["Psychological", "Drama", "Mystery", "Time Travel", "Action", "Hiatus"],
  },
  {
    title: "Rising to the Top",
    description: "An interactive story about rising to the top.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/rising-to-the-top",
    tags: ["Romance", "Celebrity", "Drama", "Slow Burn", "Comedy", "On-going"],
  },
  {
    title: "A Fanfiction Story",
    description: "A fan fiction story about a popular series.",
    imageUrl: novelImg,
    tgtLink: "https://example.com/fanfiction-story",
    tags: ["Fan Work", "Romance", "Drama", "Sports", "Oneshot", "Dropped"],
  }, 
];